development:
  adapter: mysql2
  database: cloud_leagues_development
  username: cloud_leagues
  password: cloud_leagues
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: cloud_leagues_test
  username: cloud_leagues
  password: cloud_leagues
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: cloud_leagues_production
  username: cloud_leagues
  password: cloud_leagues
  host: localhost
  pool: 5
  timeout: 5000
